### ISSUE TITLE
Overclock QL3X B150m-a question/problem

### ISSUE THREAD

**Issue by ricout** [icyleaf/EFI-ASUS-B150M-A-D3-QL3X#11]
Hi !! Sorry to ask here, its because i didnt find other way to contact you.
I have bought a QL3X , and im using a ASUS B150M-A , its working perfect, but i cant overclock.
I cant set the multiplier all cores to up 35X 
Is there any special microcodes ? Or do you have any tip please? 
Thank you so much,

**Comment by icyleaf** [comment]
In my case, this motherboard has a trigger mechanism, the first time no matter how to set it will be fixed at 35x, after the save settings reboot into the BIOS again, remember to change again and only once this value which it will successfully update the value you fill in then save it again.

**Comment by ricout** [comment]
Thanks, i will try that!!

**Comment by ricout** [comment]
Thank you @icyleaf , thank you very much!! It worked like a charm!
