### ISSUE TITLE
关于 BIOS 设置的新探索

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/EFI-ASUS-B150M-A-D3-QL3X#8]
## 前言

最近系统出了一个严重的问题：工作的时候会无故鼠标转菊花、系统和应用全部假死，只有鼠标可以移动和键盘也能够唤出 Tab Switcher 但无法真正切换应用。自这个机器安装好之后此类事件发生过 2-3 次，起初认为是 ql3x 超频到 4.1～4.3 不稳定的原因最后降到 4.0 重启就是噩梦的开始，以至于我拔了各种硬件最后定位到是镁光 MX500 的问题，从 Windows 的磁盘检测工具来说是有坏道无法修复，使用 macOS 的磁盘管理也无法修复报 `failed to read spaceman cib 12 at address 0x6e4b`  而这个板子总是因为莫名的原因就起不来了，只能扣 CMOS 电池以及万能方案拔掉所有内存条后保留一根插到第二通道

## 正文

基于上面的反复横跳我在 BIOS 重置后都要一番操作后发现有些参数不用安装 OpenCore Install Guide 的设置也能正常引导，比如： CSM 的兼容模式，不确定是不是跟我使用的 HD7770 太老的显卡有关，BIOS 引导说显卡太老建议开启 CSM 在我开启后保持默认设置开机也没问题，后续我会再尝试不动其他设置的情况下的结果如何

**Comment by keoy** [comment]
不是说镁光主控不能黑吗

**Comment by icyleaf** [comment]
没有黑主控呢，没有理解你的意思
